# Remove all files generated by tree-sitter generate,
# so I can focus the code which should be read / edited.

rm -rf bindings/
rm -rf src/
rm -rf .editorconfig
rm -rf .gitattributes
rm -rf binding.gyp
rm -rf Cargo.toml
rm -rf Makefile
rm -rf Package.swift
rm -rf pyproject.toml
rm -rf setup.py
