#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 124
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 11
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 9

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_body_block_keyword = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_SEMI = 5,
  sym_promise_block_keyword = 6,
  sym_bundle_block_keyword = 7,
  anon_sym_LPAREN = 8,
  anon_sym_COMMA = 9,
  anon_sym_RPAREN = 10,
  anon_sym_DASH_GT = 11,
  anon_sym_EQ_GT = 12,
  sym_quoted_string = 13,
  sym_qualified_identifier = 14,
  sym_promise_guard = 15,
  sym_class_guard = 16,
  sym_comment = 17,
  sym_macro = 18,
  sym_source_file = 19,
  sym__block = 20,
  sym_body_block = 21,
  sym_body_block_body = 22,
  sym__body_attribute = 23,
  sym_promise_block = 24,
  sym_promise_block_body = 25,
  sym_class_guarded_body_attributes = 26,
  sym_bundle_block = 27,
  sym_parameter_list = 28,
  sym_bundle_block_body = 29,
  sym_bundle_section = 30,
  sym__right_value = 31,
  sym_call = 32,
  sym_list = 33,
  sym__value_list = 34,
  sym_class_guarded_promises = 35,
  sym__promises = 36,
  sym_promise = 37,
  sym_half_promise = 38,
  sym_attribute = 39,
  aux_sym_source_file_repeat1 = 40,
  aux_sym_body_block_body_repeat1 = 41,
  aux_sym_body_block_body_repeat2 = 42,
  aux_sym_promise_block_body_repeat1 = 43,
  aux_sym_parameter_list_repeat1 = 44,
  aux_sym_bundle_block_body_repeat1 = 45,
  aux_sym_bundle_section_repeat1 = 46,
  aux_sym__value_list_repeat1 = 47,
  aux_sym__promises_repeat1 = 48,
  aux_sym_promise_repeat1 = 49,
  alias_sym_attribute_name = 50,
  alias_sym_body_block_name = 51,
  alias_sym_body_block_type = 52,
  alias_sym_bundle_block_name = 53,
  alias_sym_bundle_block_type = 54,
  alias_sym_calling_identifier = 55,
  alias_sym_class_guarded_promise_block_attributes = 56,
  alias_sym_promise_block_name = 57,
  alias_sym_promise_block_type = 58,
  alias_sym_promiser = 59,
  alias_sym_stakeholder = 60,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "parameter",
  [sym_body_block_keyword] = "body_block_keyword",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SEMI] = ";",
  [sym_promise_block_keyword] = "promise_block_keyword",
  [sym_bundle_block_keyword] = "bundle_block_keyword",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_EQ_GT] = "=>",
  [sym_quoted_string] = "quoted_string",
  [sym_qualified_identifier] = "qualified_identifier",
  [sym_promise_guard] = "promise_guard",
  [sym_class_guard] = "class_guard",
  [sym_comment] = "comment",
  [sym_macro] = "macro",
  [sym_source_file] = "source_file",
  [sym__block] = "_block",
  [sym_body_block] = "body_block",
  [sym_body_block_body] = "body_block_body",
  [sym__body_attribute] = "_body_attribute",
  [sym_promise_block] = "promise_block",
  [sym_promise_block_body] = "promise_block_body",
  [sym_class_guarded_body_attributes] = "class_guarded_body_attributes",
  [sym_bundle_block] = "bundle_block",
  [sym_parameter_list] = "parameter_list",
  [sym_bundle_block_body] = "bundle_block_body",
  [sym_bundle_section] = "bundle_section",
  [sym__right_value] = "_right_value",
  [sym_call] = "call",
  [sym_list] = "list",
  [sym__value_list] = "_value_list",
  [sym_class_guarded_promises] = "class_guarded_promises",
  [sym__promises] = "_promises",
  [sym_promise] = "promise",
  [sym_half_promise] = "half_promise",
  [sym_attribute] = "attribute",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_body_block_body_repeat1] = "body_block_body_repeat1",
  [aux_sym_body_block_body_repeat2] = "body_block_body_repeat2",
  [aux_sym_promise_block_body_repeat1] = "promise_block_body_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_bundle_block_body_repeat1] = "bundle_block_body_repeat1",
  [aux_sym_bundle_section_repeat1] = "bundle_section_repeat1",
  [aux_sym__value_list_repeat1] = "_value_list_repeat1",
  [aux_sym__promises_repeat1] = "_promises_repeat1",
  [aux_sym_promise_repeat1] = "promise_repeat1",
  [alias_sym_attribute_name] = "attribute_name",
  [alias_sym_body_block_name] = "body_block_name",
  [alias_sym_body_block_type] = "body_block_type",
  [alias_sym_bundle_block_name] = "bundle_block_name",
  [alias_sym_bundle_block_type] = "bundle_block_type",
  [alias_sym_calling_identifier] = "calling_identifier",
  [alias_sym_class_guarded_promise_block_attributes] = "class_guarded_promise_block_attributes",
  [alias_sym_promise_block_name] = "promise_block_name",
  [alias_sym_promise_block_type] = "promise_block_type",
  [alias_sym_promiser] = "promiser",
  [alias_sym_stakeholder] = "stakeholder",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_body_block_keyword] = sym_body_block_keyword,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_promise_block_keyword] = sym_promise_block_keyword,
  [sym_bundle_block_keyword] = sym_bundle_block_keyword,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [sym_quoted_string] = sym_quoted_string,
  [sym_qualified_identifier] = sym_qualified_identifier,
  [sym_promise_guard] = sym_promise_guard,
  [sym_class_guard] = sym_class_guard,
  [sym_comment] = sym_comment,
  [sym_macro] = sym_macro,
  [sym_source_file] = sym_source_file,
  [sym__block] = sym__block,
  [sym_body_block] = sym_body_block,
  [sym_body_block_body] = sym_body_block_body,
  [sym__body_attribute] = sym__body_attribute,
  [sym_promise_block] = sym_promise_block,
  [sym_promise_block_body] = sym_promise_block_body,
  [sym_class_guarded_body_attributes] = sym_class_guarded_body_attributes,
  [sym_bundle_block] = sym_bundle_block,
  [sym_parameter_list] = sym_parameter_list,
  [sym_bundle_block_body] = sym_bundle_block_body,
  [sym_bundle_section] = sym_bundle_section,
  [sym__right_value] = sym__right_value,
  [sym_call] = sym_call,
  [sym_list] = sym_list,
  [sym__value_list] = sym__value_list,
  [sym_class_guarded_promises] = sym_class_guarded_promises,
  [sym__promises] = sym__promises,
  [sym_promise] = sym_promise,
  [sym_half_promise] = sym_half_promise,
  [sym_attribute] = sym_attribute,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_body_block_body_repeat1] = aux_sym_body_block_body_repeat1,
  [aux_sym_body_block_body_repeat2] = aux_sym_body_block_body_repeat2,
  [aux_sym_promise_block_body_repeat1] = aux_sym_promise_block_body_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_bundle_block_body_repeat1] = aux_sym_bundle_block_body_repeat1,
  [aux_sym_bundle_section_repeat1] = aux_sym_bundle_section_repeat1,
  [aux_sym__value_list_repeat1] = aux_sym__value_list_repeat1,
  [aux_sym__promises_repeat1] = aux_sym__promises_repeat1,
  [aux_sym_promise_repeat1] = aux_sym_promise_repeat1,
  [alias_sym_attribute_name] = alias_sym_attribute_name,
  [alias_sym_body_block_name] = alias_sym_body_block_name,
  [alias_sym_body_block_type] = alias_sym_body_block_type,
  [alias_sym_bundle_block_name] = alias_sym_bundle_block_name,
  [alias_sym_bundle_block_type] = alias_sym_bundle_block_type,
  [alias_sym_calling_identifier] = alias_sym_calling_identifier,
  [alias_sym_class_guarded_promise_block_attributes] = alias_sym_class_guarded_promise_block_attributes,
  [alias_sym_promise_block_name] = alias_sym_promise_block_name,
  [alias_sym_promise_block_type] = alias_sym_promise_block_type,
  [alias_sym_promiser] = alias_sym_promiser,
  [alias_sym_stakeholder] = alias_sym_stakeholder,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_body_block_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_promise_block_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_bundle_block_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_promise_guard] = {
    .visible = true,
    .named = true,
  },
  [sym_class_guard] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_body_block] = {
    .visible = true,
    .named = true,
  },
  [sym_body_block_body] = {
    .visible = true,
    .named = true,
  },
  [sym__body_attribute] = {
    .visible = false,
    .named = true,
  },
  [sym_promise_block] = {
    .visible = true,
    .named = true,
  },
  [sym_promise_block_body] = {
    .visible = true,
    .named = true,
  },
  [sym_class_guarded_body_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_bundle_block] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_bundle_block_body] = {
    .visible = true,
    .named = true,
  },
  [sym_bundle_section] = {
    .visible = true,
    .named = true,
  },
  [sym__right_value] = {
    .visible = false,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__value_list] = {
    .visible = false,
    .named = true,
  },
  [sym_class_guarded_promises] = {
    .visible = true,
    .named = true,
  },
  [sym__promises] = {
    .visible = false,
    .named = true,
  },
  [sym_promise] = {
    .visible = true,
    .named = true,
  },
  [sym_half_promise] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_block_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_block_body_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_promise_block_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bundle_block_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bundle_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__value_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__promises_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_promise_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_body_block_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_body_block_type] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_bundle_block_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_bundle_block_type] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_calling_identifier] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_class_guarded_promise_block_attributes] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_promise_block_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_promise_block_type] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_promiser] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_stakeholder] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_body_block_type,
    [2] = alias_sym_body_block_name,
  },
  [2] = {
    [1] = alias_sym_promise_block_type,
    [2] = alias_sym_promise_block_name,
  },
  [3] = {
    [1] = alias_sym_bundle_block_type,
    [2] = alias_sym_bundle_block_name,
  },
  [4] = {
    [0] = alias_sym_class_guarded_promise_block_attributes,
  },
  [5] = {
    [0] = alias_sym_attribute_name,
  },
  [6] = {
    [0] = alias_sym_promiser,
  },
  [7] = {
    [0] = alias_sym_calling_identifier,
  },
  [8] = {
    [0] = alias_sym_promiser,
    [2] = alias_sym_stakeholder,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_class_guarded_body_attributes, 2,
    sym_class_guarded_body_attributes,
    alias_sym_class_guarded_promise_block_attributes,
  sym__right_value, 2,
    sym__right_value,
    alias_sym_stakeholder,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
};

static inline bool sym_class_guard_character_set_1(int32_t c) {
  return (c < '0'
    ? (c < '&'
      ? (c < ' '
        ? c == '\t'
        : c <= '!')
      : (c <= '&' || (c < '.'
        ? (c >= '(' && c <= ')')
        : c <= '.')))
    : (c <= '9' || (c < 'a'
      ? (c < '_'
        ? (c >= 'A' && c <= 'Z')
        : c <= '_')
      : (c <= 'z' || c == '|'))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '#') ADVANCE(43);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '(') ADVANCE(27);
      if (lookahead == ')') ADVANCE(29);
      if (lookahead == ',') ADVANCE(28);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == ';') ADVANCE(26);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == '@') ADVANCE(12);
      if (lookahead == '`') ADVANCE(10);
      if (lookahead == '{') ADVANCE(24);
      if (lookahead == '}') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(44);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '#') ADVANCE(43);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == ')') ADVANCE(29);
      if (lookahead == '@') ADVANCE(12);
      if (lookahead == '`') ADVANCE(10);
      if (lookahead == '{') ADVANCE(24);
      if (lookahead == '}') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '#') ADVANCE(43);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '@') ADVANCE(12);
      if (lookahead == '`') ADVANCE(10);
      if (lookahead == '}') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3)
      if (lookahead == '!' ||
          ('&' <= lookahead && lookahead <= ')') ||
          lookahead == '.' ||
          lookahead == ':' ||
          lookahead == '|') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(21);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(42);
      if (sym_class_guard_character_set_1(lookahead)) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(6);
      if (sym_class_guard_character_set_1(lookahead)) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(30);
      END_STATE();
    case 9:
      if (lookahead == '>') ADVANCE(31);
      END_STATE();
    case 10:
      if (lookahead == '`') ADVANCE(32);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(17);
      if (lookahead == 'i') ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(1);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(44);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 21:
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 22:
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == ' ' ||
          lookahead == '!' ||
          lookahead == '&' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == '.' ||
          lookahead == '|') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ' ||
          lookahead == '!' ||
          lookahead == '&' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == '.' ||
          lookahead == '|') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_qualified_identifier);
      if (lookahead == '.') ADVANCE(19);
      if (lookahead == ':') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_qualified_identifier);
      if (lookahead == '.') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_qualified_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_promise_guard);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_promise_guard);
      if (lookahead == ':') ADVANCE(42);
      if (sym_class_guard_character_set_1(lookahead)) ADVANCE(7);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_class_guard);
      if (lookahead == ':') ADVANCE(42);
      if (sym_class_guard_character_set_1(lookahead)) ADVANCE(7);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_macro);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'b') ADVANCE(1);
      if (lookahead == 'p') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(3);
      if (lookahead == 'u') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'd') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'y') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'm') ADVANCE(11);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_body_block_keyword);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_bundle_block_keyword);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_promise_block_keyword);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 3},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 3},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 3},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_body_block_keyword] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_promise_block_keyword] = ACTIONS(1),
    [sym_bundle_block_keyword] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_macro] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(120),
    [sym__block] = STATE(6),
    [sym_body_block] = STATE(6),
    [sym_promise_block] = STATE(6),
    [sym_bundle_block] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_body_block_keyword] = ACTIONS(7),
    [sym_promise_block_keyword] = ACTIONS(9),
    [sym_bundle_block_keyword] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
    [sym_macro] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym_body_block_keyword,
    ACTIONS(18), 1,
      sym_promise_block_keyword,
    ACTIONS(21), 1,
      sym_bundle_block_keyword,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(2), 5,
      sym__block,
      sym_body_block,
      sym_promise_block,
      sym_bundle_block,
      aux_sym_source_file_repeat1,
  [24] = 7,
    ACTIONS(24), 1,
      sym_identifier,
    ACTIONS(28), 1,
      sym_quoted_string,
    ACTIONS(30), 1,
      sym_promise_guard,
    STATE(78), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(26), 2,
      anon_sym_RBRACE,
      sym_class_guard,
    STATE(5), 3,
      sym_promise,
      sym_half_promise,
      aux_sym__promises_repeat1,
  [50] = 7,
    ACTIONS(32), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym_quoted_string,
    ACTIONS(40), 1,
      sym_promise_guard,
    STATE(78), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(35), 2,
      anon_sym_RBRACE,
      sym_class_guard,
    STATE(4), 3,
      sym_promise,
      sym_half_promise,
      aux_sym__promises_repeat1,
  [76] = 7,
    ACTIONS(24), 1,
      sym_identifier,
    ACTIONS(28), 1,
      sym_quoted_string,
    ACTIONS(44), 1,
      sym_promise_guard,
    STATE(78), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(42), 2,
      anon_sym_RBRACE,
      sym_class_guard,
    STATE(4), 3,
      sym_promise,
      sym_half_promise,
      aux_sym__promises_repeat1,
  [102] = 6,
    ACTIONS(7), 1,
      sym_body_block_keyword,
    ACTIONS(9), 1,
      sym_promise_block_keyword,
    ACTIONS(11), 1,
      sym_bundle_block_keyword,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(2), 5,
      sym__block,
      sym_body_block,
      sym_promise_block,
      sym_bundle_block,
      aux_sym_source_file_repeat1,
  [126] = 8,
    ACTIONS(24), 1,
      sym_identifier,
    ACTIONS(48), 1,
      anon_sym_RBRACE,
    ACTIONS(50), 1,
      sym_class_guard,
    STATE(46), 1,
      aux_sym_promise_block_body_repeat1,
    STATE(98), 1,
      sym_class_guarded_body_attributes,
    STATE(112), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(12), 2,
      sym__body_attribute,
      aux_sym_body_block_body_repeat1,
  [153] = 8,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(54), 1,
      anon_sym_RPAREN,
    ACTIONS(56), 1,
      sym_quoted_string,
    ACTIONS(58), 1,
      sym_qualified_identifier,
    STATE(57), 1,
      sym__right_value,
    STATE(114), 1,
      sym__value_list,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(31), 2,
      sym_call,
      sym_list,
  [180] = 8,
    ACTIONS(28), 1,
      sym_quoted_string,
    ACTIONS(60), 1,
      anon_sym_RBRACE,
    ACTIONS(62), 1,
      sym_promise_guard,
    ACTIONS(64), 1,
      sym_class_guard,
    STATE(3), 1,
      sym_promise,
    STATE(33), 1,
      sym__promises,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(30), 2,
      sym_class_guarded_promises,
      aux_sym_bundle_section_repeat1,
  [207] = 7,
    ACTIONS(24), 1,
      sym_identifier,
    ACTIONS(50), 1,
      sym_class_guard,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
    STATE(112), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(13), 2,
      sym__body_attribute,
      aux_sym_body_block_body_repeat1,
    STATE(63), 2,
      sym_class_guarded_body_attributes,
      aux_sym_body_block_body_repeat2,
  [232] = 7,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      sym_quoted_string,
    ACTIONS(58), 1,
      sym_qualified_identifier,
    STATE(83), 1,
      sym__right_value,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(68), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    STATE(31), 2,
      sym_call,
      sym_list,
  [257] = 8,
    ACTIONS(24), 1,
      sym_identifier,
    ACTIONS(50), 1,
      sym_class_guard,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    STATE(53), 1,
      aux_sym_promise_block_body_repeat1,
    STATE(98), 1,
      sym_class_guarded_body_attributes,
    STATE(112), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(19), 2,
      sym__body_attribute,
      aux_sym_body_block_body_repeat1,
  [284] = 7,
    ACTIONS(24), 1,
      sym_identifier,
    ACTIONS(50), 1,
      sym_class_guard,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    STATE(112), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(19), 2,
      sym__body_attribute,
      aux_sym_body_block_body_repeat1,
    STATE(49), 2,
      sym_class_guarded_body_attributes,
      aux_sym_body_block_body_repeat2,
  [309] = 7,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      sym_quoted_string,
    ACTIONS(58), 1,
      sym_qualified_identifier,
    STATE(83), 1,
      sym__right_value,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(74), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    STATE(31), 2,
      sym_call,
      sym_list,
  [334] = 8,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      sym_quoted_string,
    ACTIONS(58), 1,
      sym_qualified_identifier,
    ACTIONS(76), 1,
      anon_sym_RBRACE,
    STATE(57), 1,
      sym__right_value,
    STATE(113), 1,
      sym__value_list,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(31), 2,
      sym_call,
      sym_list,
  [361] = 6,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      sym_quoted_string,
    ACTIONS(58), 1,
      sym_qualified_identifier,
    STATE(96), 1,
      sym__right_value,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(31), 2,
      sym_call,
      sym_list,
  [382] = 7,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(80), 1,
      anon_sym_SEMI,
    ACTIONS(82), 1,
      anon_sym_COMMA,
    ACTIONS(84), 1,
      anon_sym_DASH_GT,
    STATE(75), 1,
      aux_sym_promise_repeat1,
    STATE(93), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [405] = 6,
    ACTIONS(28), 1,
      sym_quoted_string,
    ACTIONS(88), 1,
      sym_promise_guard,
    STATE(3), 1,
      sym_promise,
    STATE(76), 1,
      sym__promises,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(86), 2,
      anon_sym_RBRACE,
      sym_class_guard,
  [426] = 5,
    ACTIONS(90), 1,
      sym_identifier,
    STATE(112), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(93), 2,
      anon_sym_RBRACE,
      sym_class_guard,
    STATE(19), 2,
      sym__body_attribute,
      aux_sym_body_block_body_repeat1,
  [445] = 5,
    ACTIONS(24), 1,
      sym_identifier,
    STATE(112), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(95), 2,
      anon_sym_RBRACE,
      sym_class_guard,
    STATE(19), 2,
      sym__body_attribute,
      aux_sym_body_block_body_repeat1,
  [464] = 6,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      sym_quoted_string,
    ACTIONS(58), 1,
      sym_qualified_identifier,
    STATE(38), 1,
      sym__right_value,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(31), 2,
      sym_call,
      sym_list,
  [485] = 6,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    ACTIONS(56), 1,
      sym_quoted_string,
    ACTIONS(58), 1,
      sym_qualified_identifier,
    STATE(83), 1,
      sym__right_value,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(31), 2,
      sym_call,
      sym_list,
  [506] = 3,
    ACTIONS(99), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(97), 5,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
  [521] = 5,
    ACTIONS(24), 1,
      sym_identifier,
    STATE(112), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(101), 2,
      anon_sym_RBRACE,
      sym_class_guard,
    STATE(20), 2,
      sym__body_attribute,
      aux_sym_body_block_body_repeat1,
  [540] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(103), 5,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
  [552] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(105), 5,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
  [564] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(107), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(109), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [578] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(111), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(113), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [592] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(115), 5,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
  [604] = 5,
    ACTIONS(64), 1,
      sym_class_guard,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
    ACTIONS(119), 1,
      sym_promise_guard,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(37), 2,
      sym_class_guarded_promises,
      aux_sym_bundle_section_repeat1,
  [622] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(97), 5,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
  [634] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(121), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(123), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [648] = 5,
    ACTIONS(64), 1,
      sym_class_guard,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
    ACTIONS(119), 1,
      sym_promise_guard,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(36), 2,
      sym_class_guarded_promises,
      aux_sym_bundle_section_repeat1,
  [666] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(125), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(127), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [680] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(129), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(131), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [694] = 5,
    ACTIONS(64), 1,
      sym_class_guard,
    ACTIONS(133), 1,
      anon_sym_RBRACE,
    ACTIONS(135), 1,
      sym_promise_guard,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(37), 2,
      sym_class_guarded_promises,
      aux_sym_bundle_section_repeat1,
  [712] = 5,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
    ACTIONS(139), 1,
      sym_promise_guard,
    ACTIONS(141), 1,
      sym_class_guard,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(37), 2,
      sym_class_guarded_promises,
      aux_sym_bundle_section_repeat1,
  [730] = 6,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(144), 1,
      anon_sym_SEMI,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    STATE(86), 1,
      aux_sym_promise_repeat1,
    STATE(87), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [750] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(148), 5,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
  [762] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(150), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(152), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [776] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(154), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(156), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [790] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(158), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(160), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [804] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(162), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(164), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [818] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(166), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(168), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [832] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(170), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(172), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [846] = 5,
    ACTIONS(50), 1,
      sym_class_guard,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      aux_sym_promise_block_body_repeat1,
    STATE(98), 1,
      sym_class_guarded_body_attributes,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [863] = 4,
    ACTIONS(174), 1,
      anon_sym_RBRACE,
    ACTIONS(176), 1,
      sym_class_guard,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(47), 2,
      sym_class_guarded_body_attributes,
      aux_sym_body_block_body_repeat2,
  [878] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(179), 4,
      ts_builtin_sym_end,
      sym_body_block_keyword,
      sym_promise_block_keyword,
      sym_bundle_block_keyword,
  [889] = 4,
    ACTIONS(50), 1,
      sym_class_guard,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(47), 2,
      sym_class_guarded_body_attributes,
      aux_sym_body_block_body_repeat2,
  [904] = 5,
    ACTIONS(183), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_LPAREN,
    STATE(70), 1,
      sym_body_block_body,
    STATE(102), 1,
      sym_parameter_list,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [921] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(187), 4,
      ts_builtin_sym_end,
      sym_body_block_keyword,
      sym_promise_block_keyword,
      sym_bundle_block_keyword,
  [932] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(189), 4,
      ts_builtin_sym_end,
      sym_body_block_keyword,
      sym_promise_block_keyword,
      sym_bundle_block_keyword,
  [943] = 5,
    ACTIONS(50), 1,
      sym_class_guard,
    ACTIONS(191), 1,
      anon_sym_RBRACE,
    STATE(54), 1,
      aux_sym_promise_block_body_repeat1,
    STATE(98), 1,
      sym_class_guarded_body_attributes,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [960] = 5,
    ACTIONS(193), 1,
      anon_sym_RBRACE,
    ACTIONS(195), 1,
      sym_class_guard,
    STATE(54), 1,
      aux_sym_promise_block_body_repeat1,
    STATE(98), 1,
      sym_class_guarded_body_attributes,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [977] = 4,
    ACTIONS(198), 1,
      anon_sym_RBRACE,
    ACTIONS(200), 1,
      sym_promise_guard,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(61), 2,
      sym_bundle_section,
      aux_sym_bundle_block_body_repeat1,
  [992] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(202), 4,
      ts_builtin_sym_end,
      sym_body_block_keyword,
      sym_promise_block_keyword,
      sym_bundle_block_keyword,
  [1003] = 4,
    ACTIONS(206), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym__value_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(204), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
  [1018] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(208), 4,
      ts_builtin_sym_end,
      sym_body_block_keyword,
      sym_promise_block_keyword,
      sym_bundle_block_keyword,
  [1029] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(210), 4,
      ts_builtin_sym_end,
      sym_body_block_keyword,
      sym_promise_block_keyword,
      sym_bundle_block_keyword,
  [1040] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(212), 4,
      ts_builtin_sym_end,
      sym_body_block_keyword,
      sym_promise_block_keyword,
      sym_bundle_block_keyword,
  [1051] = 4,
    ACTIONS(214), 1,
      anon_sym_RBRACE,
    ACTIONS(216), 1,
      sym_promise_guard,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(61), 2,
      sym_bundle_section,
      aux_sym_bundle_block_body_repeat1,
  [1066] = 4,
    ACTIONS(219), 1,
      anon_sym_COMMA,
    STATE(72), 1,
      aux_sym__value_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(74), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
  [1081] = 4,
    ACTIONS(50), 1,
      sym_class_guard,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(47), 2,
      sym_class_guarded_body_attributes,
      aux_sym_body_block_body_repeat2,
  [1096] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(221), 4,
      ts_builtin_sym_end,
      sym_body_block_keyword,
      sym_promise_block_keyword,
      sym_bundle_block_keyword,
  [1107] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(223), 4,
      ts_builtin_sym_end,
      sym_body_block_keyword,
      sym_promise_block_keyword,
      sym_bundle_block_keyword,
  [1118] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(225), 4,
      ts_builtin_sym_end,
      sym_body_block_keyword,
      sym_promise_block_keyword,
      sym_bundle_block_keyword,
  [1129] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(227), 4,
      ts_builtin_sym_end,
      sym_body_block_keyword,
      sym_promise_block_keyword,
      sym_bundle_block_keyword,
  [1140] = 4,
    ACTIONS(200), 1,
      sym_promise_guard,
    ACTIONS(229), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(55), 2,
      sym_bundle_section,
      aux_sym_bundle_block_body_repeat1,
  [1155] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(231), 4,
      ts_builtin_sym_end,
      sym_body_block_keyword,
      sym_promise_block_keyword,
      sym_bundle_block_keyword,
  [1166] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(233), 4,
      ts_builtin_sym_end,
      sym_body_block_keyword,
      sym_promise_block_keyword,
      sym_bundle_block_keyword,
  [1177] = 5,
    ACTIONS(185), 1,
      anon_sym_LPAREN,
    ACTIONS(235), 1,
      anon_sym_LBRACE,
    STATE(67), 1,
      sym_bundle_block_body,
    STATE(103), 1,
      sym_parameter_list,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1194] = 4,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    STATE(72), 1,
      aux_sym__value_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(237), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
  [1209] = 4,
    ACTIONS(242), 1,
      anon_sym_SEMI,
    ACTIONS(244), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_promise_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1223] = 4,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(247), 1,
      anon_sym_SEMI,
    STATE(104), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1237] = 4,
    ACTIONS(249), 1,
      anon_sym_SEMI,
    ACTIONS(251), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_promise_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1251] = 3,
    ACTIONS(255), 1,
      sym_promise_guard,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(253), 2,
      anon_sym_RBRACE,
      sym_class_guard,
  [1263] = 4,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(257), 1,
      anon_sym_SEMI,
    STATE(104), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1277] = 4,
    ACTIONS(259), 1,
      anon_sym_SEMI,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    STATE(89), 1,
      aux_sym_promise_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1291] = 4,
    ACTIONS(263), 1,
      anon_sym_SEMI,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_promise_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1305] = 4,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(263), 1,
      anon_sym_SEMI,
    STATE(104), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1319] = 4,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(249), 1,
      anon_sym_SEMI,
    STATE(104), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1333] = 4,
    ACTIONS(267), 1,
      sym_identifier,
    ACTIONS(269), 1,
      anon_sym_RPAREN,
    STATE(94), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1347] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(237), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1357] = 4,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(271), 1,
      anon_sym_SEMI,
    STATE(104), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1371] = 4,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(273), 1,
      anon_sym_SEMI,
    STATE(104), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1385] = 4,
    ACTIONS(275), 1,
      anon_sym_SEMI,
    ACTIONS(277), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_promise_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1399] = 4,
    ACTIONS(275), 1,
      anon_sym_SEMI,
    ACTIONS(277), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym_promise_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1413] = 4,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(275), 1,
      anon_sym_SEMI,
    STATE(104), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1427] = 4,
    ACTIONS(247), 1,
      anon_sym_SEMI,
    ACTIONS(279), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_promise_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1441] = 4,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(281), 1,
      anon_sym_SEMI,
    STATE(104), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1455] = 4,
    ACTIONS(281), 1,
      anon_sym_SEMI,
    ACTIONS(283), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_promise_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1469] = 3,
    ACTIONS(285), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(287), 2,
      anon_sym_RBRACE,
      sym_class_guard,
  [1481] = 4,
    ACTIONS(249), 1,
      anon_sym_SEMI,
    ACTIONS(251), 1,
      anon_sym_COMMA,
    STATE(91), 1,
      aux_sym_promise_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1495] = 3,
    ACTIONS(289), 1,
      sym_identifier,
    STATE(105), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1506] = 3,
    ACTIONS(291), 1,
      sym_identifier,
    ACTIONS(293), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1517] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(295), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1526] = 3,
    ACTIONS(291), 1,
      sym_identifier,
    ACTIONS(297), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1537] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(299), 2,
      anon_sym_RBRACE,
      sym_class_guard,
  [1546] = 3,
    ACTIONS(301), 1,
      anon_sym_COMMA,
    ACTIONS(303), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1557] = 3,
    ACTIONS(297), 1,
      anon_sym_RPAREN,
    ACTIONS(305), 1,
      anon_sym_COMMA,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1568] = 3,
    ACTIONS(307), 1,
      anon_sym_LBRACE,
    STATE(69), 1,
      sym_promise_block_body,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1579] = 3,
    ACTIONS(183), 1,
      anon_sym_LBRACE,
    STATE(59), 1,
      sym_body_block_body,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1590] = 3,
    ACTIONS(235), 1,
      anon_sym_LBRACE,
    STATE(51), 1,
      sym_bundle_block_body,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1601] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(242), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1610] = 3,
    ACTIONS(309), 1,
      sym_identifier,
    STATE(105), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1621] = 3,
    ACTIONS(78), 1,
      sym_identifier,
    STATE(104), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1632] = 2,
    ACTIONS(291), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1640] = 2,
    ACTIONS(312), 1,
      anon_sym_EQ_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1648] = 2,
    ACTIONS(314), 1,
      anon_sym_COMMA,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1656] = 2,
    ACTIONS(316), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1664] = 2,
    ACTIONS(318), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1672] = 2,
    ACTIONS(320), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1680] = 2,
    ACTIONS(322), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1688] = 2,
    ACTIONS(324), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1696] = 2,
    ACTIONS(326), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1704] = 2,
    ACTIONS(328), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1712] = 2,
    ACTIONS(330), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1720] = 2,
    ACTIONS(332), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1728] = 2,
    ACTIONS(334), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1736] = 2,
    ACTIONS(336), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1744] = 2,
    ACTIONS(338), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1752] = 2,
    ACTIONS(340), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1760] = 2,
    ACTIONS(342), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 24,
  [SMALL_STATE(4)] = 50,
  [SMALL_STATE(5)] = 76,
  [SMALL_STATE(6)] = 102,
  [SMALL_STATE(7)] = 126,
  [SMALL_STATE(8)] = 153,
  [SMALL_STATE(9)] = 180,
  [SMALL_STATE(10)] = 207,
  [SMALL_STATE(11)] = 232,
  [SMALL_STATE(12)] = 257,
  [SMALL_STATE(13)] = 284,
  [SMALL_STATE(14)] = 309,
  [SMALL_STATE(15)] = 334,
  [SMALL_STATE(16)] = 361,
  [SMALL_STATE(17)] = 382,
  [SMALL_STATE(18)] = 405,
  [SMALL_STATE(19)] = 426,
  [SMALL_STATE(20)] = 445,
  [SMALL_STATE(21)] = 464,
  [SMALL_STATE(22)] = 485,
  [SMALL_STATE(23)] = 506,
  [SMALL_STATE(24)] = 521,
  [SMALL_STATE(25)] = 540,
  [SMALL_STATE(26)] = 552,
  [SMALL_STATE(27)] = 564,
  [SMALL_STATE(28)] = 578,
  [SMALL_STATE(29)] = 592,
  [SMALL_STATE(30)] = 604,
  [SMALL_STATE(31)] = 622,
  [SMALL_STATE(32)] = 634,
  [SMALL_STATE(33)] = 648,
  [SMALL_STATE(34)] = 666,
  [SMALL_STATE(35)] = 680,
  [SMALL_STATE(36)] = 694,
  [SMALL_STATE(37)] = 712,
  [SMALL_STATE(38)] = 730,
  [SMALL_STATE(39)] = 750,
  [SMALL_STATE(40)] = 762,
  [SMALL_STATE(41)] = 776,
  [SMALL_STATE(42)] = 790,
  [SMALL_STATE(43)] = 804,
  [SMALL_STATE(44)] = 818,
  [SMALL_STATE(45)] = 832,
  [SMALL_STATE(46)] = 846,
  [SMALL_STATE(47)] = 863,
  [SMALL_STATE(48)] = 878,
  [SMALL_STATE(49)] = 889,
  [SMALL_STATE(50)] = 904,
  [SMALL_STATE(51)] = 921,
  [SMALL_STATE(52)] = 932,
  [SMALL_STATE(53)] = 943,
  [SMALL_STATE(54)] = 960,
  [SMALL_STATE(55)] = 977,
  [SMALL_STATE(56)] = 992,
  [SMALL_STATE(57)] = 1003,
  [SMALL_STATE(58)] = 1018,
  [SMALL_STATE(59)] = 1029,
  [SMALL_STATE(60)] = 1040,
  [SMALL_STATE(61)] = 1051,
  [SMALL_STATE(62)] = 1066,
  [SMALL_STATE(63)] = 1081,
  [SMALL_STATE(64)] = 1096,
  [SMALL_STATE(65)] = 1107,
  [SMALL_STATE(66)] = 1118,
  [SMALL_STATE(67)] = 1129,
  [SMALL_STATE(68)] = 1140,
  [SMALL_STATE(69)] = 1155,
  [SMALL_STATE(70)] = 1166,
  [SMALL_STATE(71)] = 1177,
  [SMALL_STATE(72)] = 1194,
  [SMALL_STATE(73)] = 1209,
  [SMALL_STATE(74)] = 1223,
  [SMALL_STATE(75)] = 1237,
  [SMALL_STATE(76)] = 1251,
  [SMALL_STATE(77)] = 1263,
  [SMALL_STATE(78)] = 1277,
  [SMALL_STATE(79)] = 1291,
  [SMALL_STATE(80)] = 1305,
  [SMALL_STATE(81)] = 1319,
  [SMALL_STATE(82)] = 1333,
  [SMALL_STATE(83)] = 1347,
  [SMALL_STATE(84)] = 1357,
  [SMALL_STATE(85)] = 1371,
  [SMALL_STATE(86)] = 1385,
  [SMALL_STATE(87)] = 1399,
  [SMALL_STATE(88)] = 1413,
  [SMALL_STATE(89)] = 1427,
  [SMALL_STATE(90)] = 1441,
  [SMALL_STATE(91)] = 1455,
  [SMALL_STATE(92)] = 1469,
  [SMALL_STATE(93)] = 1481,
  [SMALL_STATE(94)] = 1495,
  [SMALL_STATE(95)] = 1506,
  [SMALL_STATE(96)] = 1517,
  [SMALL_STATE(97)] = 1526,
  [SMALL_STATE(98)] = 1537,
  [SMALL_STATE(99)] = 1546,
  [SMALL_STATE(100)] = 1557,
  [SMALL_STATE(101)] = 1568,
  [SMALL_STATE(102)] = 1579,
  [SMALL_STATE(103)] = 1590,
  [SMALL_STATE(104)] = 1601,
  [SMALL_STATE(105)] = 1610,
  [SMALL_STATE(106)] = 1621,
  [SMALL_STATE(107)] = 1632,
  [SMALL_STATE(108)] = 1640,
  [SMALL_STATE(109)] = 1648,
  [SMALL_STATE(110)] = 1656,
  [SMALL_STATE(111)] = 1664,
  [SMALL_STATE(112)] = 1672,
  [SMALL_STATE(113)] = 1680,
  [SMALL_STATE(114)] = 1688,
  [SMALL_STATE(115)] = 1696,
  [SMALL_STATE(116)] = 1704,
  [SMALL_STATE(117)] = 1712,
  [SMALL_STATE(118)] = 1720,
  [SMALL_STATE(119)] = 1728,
  [SMALL_STATE(120)] = 1736,
  [SMALL_STATE(121)] = 1744,
  [SMALL_STATE(122)] = 1752,
  [SMALL_STATE(123)] = 1760,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(111),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(123),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(121),
  [24] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__promises, 1),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__promises, 1),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__promises_repeat1, 2), SHIFT_REPEAT(108),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__promises_repeat1, 2),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__promises_repeat1, 2), SHIFT_REPEAT(17),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__promises_repeat1, 2),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__promises, 2),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__promises, 2),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bundle_section, 1),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bundle_section, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value_list, 3),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value_list, 2),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_guarded_promises, 1),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_guarded_promises, 1),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_block_body_repeat1, 2), SHIFT_REPEAT(108),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_block_body_repeat1, 2),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_guarded_body_attributes, 2),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__right_value, 1),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_guarded_body_attributes, 1),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, .production_id = 7),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_promise, 4, .production_id = 8),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise, 4, .production_id = 8),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_promise, 7, .production_id = 8),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise, 7, .production_id = 8),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bundle_section, 2),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bundle_section, 2),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_promise, 4, .production_id = 6),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise, 4, .production_id = 6),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_promise, 2, .production_id = 6),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise, 2, .production_id = 6),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_half_promise, 3),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_half_promise, 3),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bundle_section, 3),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bundle_section, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bundle_section_repeat1, 2),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_bundle_section_repeat1, 2),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bundle_section_repeat1, 2), SHIFT_REPEAT(18),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, .production_id = 7),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_promise, 3, .production_id = 6),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise, 3, .production_id = 6),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_promise, 5, .production_id = 8),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise, 5, .production_id = 8),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_promise, 5, .production_id = 6),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise, 5, .production_id = 6),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_half_promise, 2),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_half_promise, 2),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_half_promise, 4),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_half_promise, 4),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_promise, 6, .production_id = 8),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise, 6, .production_id = 8),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_block_body_repeat2, 2),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_block_body_repeat2, 2), SHIFT_REPEAT(24),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_block_body, 3),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bundle_block, 5, .production_id = 3),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise_block_body, 3),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_promise_block_body_repeat1, 2),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_promise_block_body_repeat1, 2), SHIFT_REPEAT(24),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bundle_block_body, 2),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value_list, 1),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise_block_body, 2),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_block, 5, .production_id = 1),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bundle_block_body, 3),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bundle_block_body_repeat1, 2),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bundle_block_body_repeat1, 2), SHIFT_REPEAT(9),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_block_body, 2),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_block_body, 4),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise_block_body, 4),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bundle_block, 4, .production_id = 3),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise_block, 4, .production_id = 2),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_block, 4, .production_id = 1),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__value_list_repeat1, 2),
  [239] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__value_list_repeat1, 2), SHIFT_REPEAT(22),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_promise_repeat1, 2),
  [244] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_promise_repeat1, 2), SHIFT_REPEAT(106),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_guarded_promises, 2),
  [255] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_guarded_promises, 2),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [285] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__body_attribute, 2),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__body_attribute, 2),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, .production_id = 5),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_promise_block_body_repeat1, 1, .production_id = 4),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [309] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(109),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 5),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [336] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cfengine() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
