#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 111
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 8
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 7

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_body_keyword = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_SEMI = 5,
  sym_bundle_keyword = 6,
  anon_sym_LPAREN = 7,
  anon_sym_COMMA = 8,
  anon_sym_RPAREN = 9,
  anon_sym_DASH_GT = 10,
  anon_sym_EQ_GT = 11,
  sym_quoted_string = 12,
  sym_qualified_identifier = 13,
  sym_promise_guard = 14,
  sym_class_guard = 15,
  sym_comment = 16,
  sym_macro = 17,
  sym_source_file = 18,
  sym__block = 19,
  sym_body_block = 20,
  sym_body_body = 21,
  sym__body_attribute = 22,
  sym_class_guarded_body_attributes = 23,
  sym_bundle_block = 24,
  sym_parameter_list = 25,
  sym_bundle_body = 26,
  sym_bundle_section = 27,
  sym__right_value = 28,
  sym_call = 29,
  sym_list = 30,
  sym__value_list = 31,
  sym_class_guarded_promises = 32,
  sym__promises = 33,
  sym_promise = 34,
  sym_half_promise = 35,
  sym_attribute = 36,
  aux_sym_source_file_repeat1 = 37,
  aux_sym_body_body_repeat1 = 38,
  aux_sym_body_body_repeat2 = 39,
  aux_sym_parameter_list_repeat1 = 40,
  aux_sym_bundle_body_repeat1 = 41,
  aux_sym_bundle_section_repeat1 = 42,
  aux_sym__value_list_repeat1 = 43,
  aux_sym__promises_repeat1 = 44,
  aux_sym_promise_repeat1 = 45,
  alias_sym_attribute_name = 46,
  alias_sym_body_name = 47,
  alias_sym_body_type = 48,
  alias_sym_bundle_name = 49,
  alias_sym_bundle_type = 50,
  alias_sym_calling_identifier = 51,
  alias_sym_promiser = 52,
  alias_sym_stakeholder = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "parameter",
  [sym_body_keyword] = "body_keyword",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SEMI] = ";",
  [sym_bundle_keyword] = "bundle_keyword",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_EQ_GT] = "=>",
  [sym_quoted_string] = "quoted_string",
  [sym_qualified_identifier] = "qualified_identifier",
  [sym_promise_guard] = "promise_guard",
  [sym_class_guard] = "class_guard",
  [sym_comment] = "comment",
  [sym_macro] = "macro",
  [sym_source_file] = "source_file",
  [sym__block] = "_block",
  [sym_body_block] = "body_block",
  [sym_body_body] = "body_body",
  [sym__body_attribute] = "_body_attribute",
  [sym_class_guarded_body_attributes] = "class_guarded_body_attributes",
  [sym_bundle_block] = "bundle_block",
  [sym_parameter_list] = "parameter_list",
  [sym_bundle_body] = "bundle_body",
  [sym_bundle_section] = "bundle_section",
  [sym__right_value] = "_right_value",
  [sym_call] = "call",
  [sym_list] = "list",
  [sym__value_list] = "_value_list",
  [sym_class_guarded_promises] = "class_guarded_promises",
  [sym__promises] = "_promises",
  [sym_promise] = "promise",
  [sym_half_promise] = "half_promise",
  [sym_attribute] = "attribute",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_body_body_repeat1] = "body_body_repeat1",
  [aux_sym_body_body_repeat2] = "body_body_repeat2",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_bundle_body_repeat1] = "bundle_body_repeat1",
  [aux_sym_bundle_section_repeat1] = "bundle_section_repeat1",
  [aux_sym__value_list_repeat1] = "_value_list_repeat1",
  [aux_sym__promises_repeat1] = "_promises_repeat1",
  [aux_sym_promise_repeat1] = "promise_repeat1",
  [alias_sym_attribute_name] = "attribute_name",
  [alias_sym_body_name] = "body_name",
  [alias_sym_body_type] = "body_type",
  [alias_sym_bundle_name] = "bundle_name",
  [alias_sym_bundle_type] = "bundle_type",
  [alias_sym_calling_identifier] = "calling_identifier",
  [alias_sym_promiser] = "promiser",
  [alias_sym_stakeholder] = "stakeholder",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_body_keyword] = sym_body_keyword,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_bundle_keyword] = sym_bundle_keyword,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [sym_quoted_string] = sym_quoted_string,
  [sym_qualified_identifier] = sym_qualified_identifier,
  [sym_promise_guard] = sym_promise_guard,
  [sym_class_guard] = sym_class_guard,
  [sym_comment] = sym_comment,
  [sym_macro] = sym_macro,
  [sym_source_file] = sym_source_file,
  [sym__block] = sym__block,
  [sym_body_block] = sym_body_block,
  [sym_body_body] = sym_body_body,
  [sym__body_attribute] = sym__body_attribute,
  [sym_class_guarded_body_attributes] = sym_class_guarded_body_attributes,
  [sym_bundle_block] = sym_bundle_block,
  [sym_parameter_list] = sym_parameter_list,
  [sym_bundle_body] = sym_bundle_body,
  [sym_bundle_section] = sym_bundle_section,
  [sym__right_value] = sym__right_value,
  [sym_call] = sym_call,
  [sym_list] = sym_list,
  [sym__value_list] = sym__value_list,
  [sym_class_guarded_promises] = sym_class_guarded_promises,
  [sym__promises] = sym__promises,
  [sym_promise] = sym_promise,
  [sym_half_promise] = sym_half_promise,
  [sym_attribute] = sym_attribute,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_body_body_repeat1] = aux_sym_body_body_repeat1,
  [aux_sym_body_body_repeat2] = aux_sym_body_body_repeat2,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_bundle_body_repeat1] = aux_sym_bundle_body_repeat1,
  [aux_sym_bundle_section_repeat1] = aux_sym_bundle_section_repeat1,
  [aux_sym__value_list_repeat1] = aux_sym__value_list_repeat1,
  [aux_sym__promises_repeat1] = aux_sym__promises_repeat1,
  [aux_sym_promise_repeat1] = aux_sym_promise_repeat1,
  [alias_sym_attribute_name] = alias_sym_attribute_name,
  [alias_sym_body_name] = alias_sym_body_name,
  [alias_sym_body_type] = alias_sym_body_type,
  [alias_sym_bundle_name] = alias_sym_bundle_name,
  [alias_sym_bundle_type] = alias_sym_bundle_type,
  [alias_sym_calling_identifier] = alias_sym_calling_identifier,
  [alias_sym_promiser] = alias_sym_promiser,
  [alias_sym_stakeholder] = alias_sym_stakeholder,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_body_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_bundle_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_promise_guard] = {
    .visible = true,
    .named = true,
  },
  [sym_class_guard] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_body_block] = {
    .visible = true,
    .named = true,
  },
  [sym_body_body] = {
    .visible = true,
    .named = true,
  },
  [sym__body_attribute] = {
    .visible = false,
    .named = true,
  },
  [sym_class_guarded_body_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_bundle_block] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_bundle_body] = {
    .visible = true,
    .named = true,
  },
  [sym_bundle_section] = {
    .visible = true,
    .named = true,
  },
  [sym__right_value] = {
    .visible = false,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__value_list] = {
    .visible = false,
    .named = true,
  },
  [sym_class_guarded_promises] = {
    .visible = true,
    .named = true,
  },
  [sym__promises] = {
    .visible = false,
    .named = true,
  },
  [sym_promise] = {
    .visible = true,
    .named = true,
  },
  [sym_half_promise] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_body_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bundle_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_bundle_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__value_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__promises_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_promise_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_body_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_body_type] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_bundle_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_bundle_type] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_calling_identifier] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_promiser] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_stakeholder] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_body_type,
    [2] = alias_sym_body_name,
  },
  [2] = {
    [1] = alias_sym_bundle_type,
    [2] = alias_sym_bundle_name,
  },
  [3] = {
    [0] = alias_sym_attribute_name,
  },
  [4] = {
    [0] = alias_sym_promiser,
  },
  [5] = {
    [0] = alias_sym_calling_identifier,
  },
  [6] = {
    [0] = alias_sym_promiser,
    [2] = alias_sym_stakeholder,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__right_value, 2,
    sym__right_value,
    alias_sym_stakeholder,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
};

static inline bool sym_class_guard_character_set_1(int32_t c) {
  return (c < '0'
    ? (c < '&'
      ? (c < ' '
        ? c == '\t'
        : c <= '!')
      : (c <= '&' || (c < '.'
        ? (c >= '(' && c <= ')')
        : c <= '.')))
    : (c <= '9' || (c < 'a'
      ? (c < '_'
        ? (c >= 'A' && c <= 'Z')
        : c <= '_')
      : (c <= 'z' || c == '|'))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '#') ADVANCE(43);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '(') ADVANCE(27);
      if (lookahead == ')') ADVANCE(29);
      if (lookahead == ',') ADVANCE(28);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == ';') ADVANCE(26);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == '@') ADVANCE(12);
      if (lookahead == '`') ADVANCE(10);
      if (lookahead == '{') ADVANCE(24);
      if (lookahead == '}') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(44);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '#') ADVANCE(43);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == ')') ADVANCE(29);
      if (lookahead == '@') ADVANCE(12);
      if (lookahead == '`') ADVANCE(10);
      if (lookahead == '{') ADVANCE(24);
      if (lookahead == '}') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '#') ADVANCE(43);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '@') ADVANCE(12);
      if (lookahead == '`') ADVANCE(10);
      if (lookahead == '}') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3)
      if (lookahead == '!' ||
          ('&' <= lookahead && lookahead <= ')') ||
          lookahead == '.' ||
          lookahead == ':' ||
          lookahead == '|') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(21);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(42);
      if (sym_class_guard_character_set_1(lookahead)) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(6);
      if (sym_class_guard_character_set_1(lookahead)) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(30);
      END_STATE();
    case 9:
      if (lookahead == '>') ADVANCE(31);
      END_STATE();
    case 10:
      if (lookahead == '`') ADVANCE(32);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(17);
      if (lookahead == 'i') ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(1);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(44);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 21:
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 22:
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == ' ' ||
          lookahead == '!' ||
          lookahead == '&' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == '.' ||
          lookahead == '|') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ' ||
          lookahead == '!' ||
          lookahead == '&' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == '.' ||
          lookahead == '|') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_qualified_identifier);
      if (lookahead == '.') ADVANCE(19);
      if (lookahead == ':') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_qualified_identifier);
      if (lookahead == '.') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_qualified_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_promise_guard);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_promise_guard);
      if (lookahead == ':') ADVANCE(42);
      if (sym_class_guard_character_set_1(lookahead)) ADVANCE(7);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_class_guard);
      if (lookahead == ':') ADVANCE(42);
      if (sym_class_guard_character_set_1(lookahead)) ADVANCE(7);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_macro);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'b') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(2);
      if (lookahead == 'u') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == 'd') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == 'y') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == 'd') ADVANCE(7);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_body_keyword);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_bundle_keyword);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 3},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_body_keyword] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_bundle_keyword] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_macro] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(108),
    [sym__block] = STATE(12),
    [sym_body_block] = STATE(12),
    [sym_bundle_block] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_body_keyword] = ACTIONS(7),
    [sym_bundle_keyword] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [sym_macro] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_quoted_string,
    ACTIONS(17), 1,
      sym_promise_guard,
    STATE(65), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(13), 2,
      anon_sym_RBRACE,
      sym_class_guard,
    STATE(4), 3,
      sym_promise,
      sym_half_promise,
      aux_sym__promises_repeat1,
  [26] = 7,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(15), 1,
      sym_quoted_string,
    ACTIONS(21), 1,
      sym_promise_guard,
    STATE(65), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(19), 2,
      anon_sym_RBRACE,
      sym_class_guard,
    STATE(2), 3,
      sym_promise,
      sym_half_promise,
      aux_sym__promises_repeat1,
  [52] = 7,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(28), 1,
      sym_quoted_string,
    ACTIONS(31), 1,
      sym_promise_guard,
    STATE(65), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(26), 2,
      anon_sym_RBRACE,
      sym_class_guard,
    STATE(4), 3,
      sym_promise,
      sym_half_promise,
      aux_sym__promises_repeat1,
  [78] = 8,
    ACTIONS(15), 1,
      sym_quoted_string,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(35), 1,
      sym_promise_guard,
    ACTIONS(37), 1,
      sym_class_guard,
    STATE(3), 1,
      sym_promise,
    STATE(24), 1,
      sym__promises,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(38), 2,
      sym_class_guarded_promises,
      aux_sym_bundle_section_repeat1,
  [105] = 7,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    ACTIONS(41), 1,
      sym_class_guard,
    STATE(102), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(18), 2,
      sym__body_attribute,
      aux_sym_body_body_repeat1,
    STATE(50), 2,
      sym_class_guarded_body_attributes,
      aux_sym_body_body_repeat2,
  [130] = 7,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      sym_quoted_string,
    ACTIONS(49), 1,
      sym_qualified_identifier,
    STATE(70), 1,
      sym__right_value,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(45), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    STATE(36), 2,
      sym_call,
      sym_list,
  [155] = 8,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      sym_quoted_string,
    ACTIONS(49), 1,
      sym_qualified_identifier,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(44), 1,
      sym__right_value,
    STATE(107), 1,
      sym__value_list,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(36), 2,
      sym_call,
      sym_list,
  [182] = 7,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(41), 1,
      sym_class_guard,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    STATE(102), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(6), 2,
      sym__body_attribute,
      aux_sym_body_body_repeat1,
    STATE(54), 2,
      sym_class_guarded_body_attributes,
      aux_sym_body_body_repeat2,
  [207] = 8,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      sym_quoted_string,
    ACTIONS(49), 1,
      sym_qualified_identifier,
    ACTIONS(55), 1,
      anon_sym_RPAREN,
    STATE(44), 1,
      sym__right_value,
    STATE(103), 1,
      sym__value_list,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(36), 2,
      sym_call,
      sym_list,
  [234] = 7,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      sym_quoted_string,
    ACTIONS(49), 1,
      sym_qualified_identifier,
    STATE(70), 1,
      sym__right_value,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(57), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
    STATE(36), 2,
      sym_call,
      sym_list,
  [259] = 5,
    ACTIONS(7), 1,
      sym_body_keyword,
    ACTIONS(9), 1,
      sym_bundle_keyword,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(13), 4,
      sym__block,
      sym_body_block,
      sym_bundle_block,
      aux_sym_source_file_repeat1,
  [279] = 5,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(63), 1,
      sym_body_keyword,
    ACTIONS(66), 1,
      sym_bundle_keyword,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(13), 4,
      sym__block,
      sym_body_block,
      sym_bundle_block,
      aux_sym_source_file_repeat1,
  [299] = 6,
    ACTIONS(15), 1,
      sym_quoted_string,
    ACTIONS(71), 1,
      sym_promise_guard,
    STATE(3), 1,
      sym_promise,
    STATE(63), 1,
      sym__promises,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(69), 2,
      anon_sym_RBRACE,
      sym_class_guard,
  [320] = 5,
    ACTIONS(11), 1,
      sym_identifier,
    STATE(102), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(73), 2,
      anon_sym_RBRACE,
      sym_class_guard,
    STATE(18), 2,
      sym__body_attribute,
      aux_sym_body_body_repeat1,
  [339] = 7,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(77), 1,
      anon_sym_SEMI,
    ACTIONS(79), 1,
      anon_sym_COMMA,
    ACTIONS(81), 1,
      anon_sym_DASH_GT,
    STATE(61), 1,
      sym_attribute,
    STATE(62), 1,
      aux_sym_promise_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [362] = 6,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      sym_quoted_string,
    ACTIONS(49), 1,
      sym_qualified_identifier,
    STATE(85), 1,
      sym__right_value,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(36), 2,
      sym_call,
      sym_list,
  [383] = 5,
    ACTIONS(83), 1,
      sym_identifier,
    STATE(102), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(86), 2,
      anon_sym_RBRACE,
      sym_class_guard,
    STATE(18), 2,
      sym__body_attribute,
      aux_sym_body_body_repeat1,
  [402] = 6,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      sym_quoted_string,
    ACTIONS(49), 1,
      sym_qualified_identifier,
    STATE(34), 1,
      sym__right_value,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(36), 2,
      sym_call,
      sym_list,
  [423] = 5,
    ACTIONS(11), 1,
      sym_identifier,
    STATE(102), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(88), 2,
      anon_sym_RBRACE,
      sym_class_guard,
    STATE(15), 2,
      sym__body_attribute,
      aux_sym_body_body_repeat1,
  [442] = 6,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      sym_quoted_string,
    ACTIONS(49), 1,
      sym_qualified_identifier,
    STATE(70), 1,
      sym__right_value,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(36), 2,
      sym_call,
      sym_list,
  [463] = 3,
    ACTIONS(92), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(90), 5,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
  [478] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(94), 5,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
  [490] = 5,
    ACTIONS(37), 1,
      sym_class_guard,
    ACTIONS(96), 1,
      anon_sym_RBRACE,
    ACTIONS(98), 1,
      sym_promise_guard,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(27), 2,
      sym_class_guarded_promises,
      aux_sym_bundle_section_repeat1,
  [508] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(100), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(102), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [522] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(104), 5,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
  [534] = 5,
    ACTIONS(37), 1,
      sym_class_guard,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    ACTIONS(108), 1,
      sym_promise_guard,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(42), 2,
      sym_class_guarded_promises,
      aux_sym_bundle_section_repeat1,
  [552] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(110), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(112), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [566] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(114), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(116), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [580] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(118), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(120), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [594] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(122), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(124), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [608] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(126), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(128), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [622] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(130), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(132), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [636] = 6,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(134), 1,
      anon_sym_SEMI,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_promise_repeat1,
    STATE(74), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [656] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(138), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(140), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [670] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(90), 5,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
  [682] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(142), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(144), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [696] = 5,
    ACTIONS(37), 1,
      sym_class_guard,
    ACTIONS(96), 1,
      anon_sym_RBRACE,
    ACTIONS(98), 1,
      sym_promise_guard,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(42), 2,
      sym_class_guarded_promises,
      aux_sym_bundle_section_repeat1,
  [714] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(146), 5,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
  [726] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(148), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(150), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [740] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(152), 5,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_identifier,
  [752] = 5,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    ACTIONS(156), 1,
      sym_promise_guard,
    ACTIONS(158), 1,
      sym_class_guard,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(42), 2,
      sym_class_guarded_promises,
      aux_sym_bundle_section_repeat1,
  [770] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(161), 2,
      sym_identifier,
      sym_promise_guard,
    ACTIONS(163), 3,
      anon_sym_RBRACE,
      sym_quoted_string,
      sym_class_guard,
  [784] = 4,
    ACTIONS(167), 1,
      anon_sym_COMMA,
    STATE(53), 1,
      aux_sym__value_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(165), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
  [799] = 4,
    ACTIONS(171), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      aux_sym__value_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(169), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
  [814] = 5,
    ACTIONS(174), 1,
      anon_sym_LBRACE,
    ACTIONS(176), 1,
      anon_sym_LPAREN,
    STATE(69), 1,
      sym_bundle_body,
    STATE(92), 1,
      sym_parameter_list,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [831] = 4,
    ACTIONS(178), 1,
      anon_sym_RBRACE,
    ACTIONS(180), 1,
      sym_class_guard,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(47), 2,
      sym_class_guarded_body_attributes,
      aux_sym_body_body_repeat2,
  [846] = 5,
    ACTIONS(176), 1,
      anon_sym_LPAREN,
    ACTIONS(183), 1,
      anon_sym_LBRACE,
    STATE(68), 1,
      sym_body_body,
    STATE(89), 1,
      sym_parameter_list,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [863] = 4,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
    ACTIONS(187), 1,
      sym_promise_guard,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(49), 2,
      sym_bundle_section,
      aux_sym_bundle_body_repeat1,
  [878] = 4,
    ACTIONS(41), 1,
      sym_class_guard,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(47), 2,
      sym_class_guarded_body_attributes,
      aux_sym_body_body_repeat2,
  [893] = 4,
    ACTIONS(192), 1,
      anon_sym_RBRACE,
    ACTIONS(194), 1,
      sym_promise_guard,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(52), 2,
      sym_bundle_section,
      aux_sym_bundle_body_repeat1,
  [908] = 4,
    ACTIONS(194), 1,
      sym_promise_guard,
    ACTIONS(196), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(49), 2,
      sym_bundle_section,
      aux_sym_bundle_body_repeat1,
  [923] = 4,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      aux_sym__value_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(45), 2,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
  [938] = 4,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    ACTIONS(41), 1,
      sym_class_guard,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    STATE(47), 2,
      sym_class_guarded_body_attributes,
      aux_sym_body_body_repeat2,
  [953] = 4,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(200), 1,
      anon_sym_SEMI,
    STATE(90), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [967] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(202), 3,
      ts_builtin_sym_end,
      sym_body_keyword,
      sym_bundle_keyword,
  [977] = 4,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(204), 1,
      anon_sym_SEMI,
    STATE(90), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [991] = 4,
    ACTIONS(206), 1,
      sym_identifier,
    ACTIONS(208), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1005] = 4,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(210), 1,
      anon_sym_SEMI,
    STATE(90), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1019] = 4,
    ACTIONS(212), 1,
      anon_sym_SEMI,
    ACTIONS(214), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym_promise_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1033] = 4,
    ACTIONS(210), 1,
      anon_sym_SEMI,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      aux_sym_promise_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1047] = 4,
    ACTIONS(210), 1,
      anon_sym_SEMI,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym_promise_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1061] = 3,
    ACTIONS(220), 1,
      sym_promise_guard,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(218), 2,
      anon_sym_RBRACE,
      sym_class_guard,
  [1073] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(222), 3,
      ts_builtin_sym_end,
      sym_body_keyword,
      sym_bundle_keyword,
  [1083] = 4,
    ACTIONS(224), 1,
      anon_sym_SEMI,
    ACTIONS(226), 1,
      anon_sym_COMMA,
    STATE(82), 1,
      aux_sym_promise_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1097] = 4,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(212), 1,
      anon_sym_SEMI,
    STATE(90), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1111] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(228), 3,
      ts_builtin_sym_end,
      sym_body_keyword,
      sym_bundle_keyword,
  [1121] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(230), 3,
      ts_builtin_sym_end,
      sym_body_keyword,
      sym_bundle_keyword,
  [1131] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(232), 3,
      ts_builtin_sym_end,
      sym_body_keyword,
      sym_bundle_keyword,
  [1141] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(169), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1151] = 4,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(234), 1,
      anon_sym_SEMI,
    STATE(90), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1165] = 4,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(236), 1,
      anon_sym_SEMI,
    STATE(90), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1179] = 4,
    ACTIONS(238), 1,
      anon_sym_SEMI,
    ACTIONS(240), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym_promise_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1193] = 4,
    ACTIONS(238), 1,
      anon_sym_SEMI,
    ACTIONS(240), 1,
      anon_sym_COMMA,
    STATE(60), 1,
      aux_sym_promise_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1207] = 4,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(238), 1,
      anon_sym_SEMI,
    STATE(90), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1221] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(242), 3,
      ts_builtin_sym_end,
      sym_body_keyword,
      sym_bundle_keyword,
  [1231] = 4,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(244), 1,
      anon_sym_SEMI,
    STATE(90), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1245] = 4,
    ACTIONS(244), 1,
      anon_sym_SEMI,
    ACTIONS(246), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym_promise_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1259] = 4,
    ACTIONS(248), 1,
      anon_sym_SEMI,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym_promise_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1273] = 3,
    ACTIONS(253), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(255), 2,
      anon_sym_RBRACE,
      sym_class_guard,
  [1285] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(257), 3,
      ts_builtin_sym_end,
      sym_body_keyword,
      sym_bundle_keyword,
  [1295] = 4,
    ACTIONS(200), 1,
      anon_sym_SEMI,
    ACTIONS(259), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym_promise_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1309] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(261), 3,
      ts_builtin_sym_end,
      sym_body_keyword,
      sym_bundle_keyword,
  [1319] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(263), 3,
      ts_builtin_sym_end,
      sym_body_keyword,
      sym_bundle_keyword,
  [1329] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(265), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1338] = 3,
    ACTIONS(267), 1,
      sym_identifier,
    ACTIONS(269), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1349] = 3,
    ACTIONS(271), 1,
      anon_sym_COMMA,
    ACTIONS(273), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1360] = 3,
    ACTIONS(275), 1,
      sym_identifier,
    STATE(88), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1371] = 3,
    ACTIONS(183), 1,
      anon_sym_LBRACE,
    STATE(84), 1,
      sym_body_body,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1382] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
    ACTIONS(248), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1391] = 3,
    ACTIONS(267), 1,
      sym_identifier,
    ACTIONS(273), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1402] = 3,
    ACTIONS(174), 1,
      anon_sym_LBRACE,
    STATE(81), 1,
      sym_bundle_body,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1413] = 3,
    ACTIONS(278), 1,
      sym_identifier,
    STATE(88), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1424] = 3,
    ACTIONS(280), 1,
      anon_sym_COMMA,
    ACTIONS(282), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1435] = 3,
    ACTIONS(75), 1,
      sym_identifier,
    STATE(90), 1,
      sym_attribute,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1446] = 2,
    ACTIONS(284), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1454] = 2,
    ACTIONS(286), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1462] = 2,
    ACTIONS(288), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1470] = 2,
    ACTIONS(290), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1478] = 2,
    ACTIONS(292), 1,
      anon_sym_EQ_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1486] = 2,
    ACTIONS(267), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1494] = 2,
    ACTIONS(294), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1502] = 2,
    ACTIONS(296), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1510] = 2,
    ACTIONS(298), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1518] = 2,
    ACTIONS(300), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1526] = 2,
    ACTIONS(302), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1534] = 2,
    ACTIONS(304), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1542] = 2,
    ACTIONS(306), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1550] = 2,
    ACTIONS(308), 1,
      anon_sym_COMMA,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
  [1558] = 2,
    ACTIONS(310), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment,
      sym_macro,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 52,
  [SMALL_STATE(5)] = 78,
  [SMALL_STATE(6)] = 105,
  [SMALL_STATE(7)] = 130,
  [SMALL_STATE(8)] = 155,
  [SMALL_STATE(9)] = 182,
  [SMALL_STATE(10)] = 207,
  [SMALL_STATE(11)] = 234,
  [SMALL_STATE(12)] = 259,
  [SMALL_STATE(13)] = 279,
  [SMALL_STATE(14)] = 299,
  [SMALL_STATE(15)] = 320,
  [SMALL_STATE(16)] = 339,
  [SMALL_STATE(17)] = 362,
  [SMALL_STATE(18)] = 383,
  [SMALL_STATE(19)] = 402,
  [SMALL_STATE(20)] = 423,
  [SMALL_STATE(21)] = 442,
  [SMALL_STATE(22)] = 463,
  [SMALL_STATE(23)] = 478,
  [SMALL_STATE(24)] = 490,
  [SMALL_STATE(25)] = 508,
  [SMALL_STATE(26)] = 522,
  [SMALL_STATE(27)] = 534,
  [SMALL_STATE(28)] = 552,
  [SMALL_STATE(29)] = 566,
  [SMALL_STATE(30)] = 580,
  [SMALL_STATE(31)] = 594,
  [SMALL_STATE(32)] = 608,
  [SMALL_STATE(33)] = 622,
  [SMALL_STATE(34)] = 636,
  [SMALL_STATE(35)] = 656,
  [SMALL_STATE(36)] = 670,
  [SMALL_STATE(37)] = 682,
  [SMALL_STATE(38)] = 696,
  [SMALL_STATE(39)] = 714,
  [SMALL_STATE(40)] = 726,
  [SMALL_STATE(41)] = 740,
  [SMALL_STATE(42)] = 752,
  [SMALL_STATE(43)] = 770,
  [SMALL_STATE(44)] = 784,
  [SMALL_STATE(45)] = 799,
  [SMALL_STATE(46)] = 814,
  [SMALL_STATE(47)] = 831,
  [SMALL_STATE(48)] = 846,
  [SMALL_STATE(49)] = 863,
  [SMALL_STATE(50)] = 878,
  [SMALL_STATE(51)] = 893,
  [SMALL_STATE(52)] = 908,
  [SMALL_STATE(53)] = 923,
  [SMALL_STATE(54)] = 938,
  [SMALL_STATE(55)] = 953,
  [SMALL_STATE(56)] = 967,
  [SMALL_STATE(57)] = 977,
  [SMALL_STATE(58)] = 991,
  [SMALL_STATE(59)] = 1005,
  [SMALL_STATE(60)] = 1019,
  [SMALL_STATE(61)] = 1033,
  [SMALL_STATE(62)] = 1047,
  [SMALL_STATE(63)] = 1061,
  [SMALL_STATE(64)] = 1073,
  [SMALL_STATE(65)] = 1083,
  [SMALL_STATE(66)] = 1097,
  [SMALL_STATE(67)] = 1111,
  [SMALL_STATE(68)] = 1121,
  [SMALL_STATE(69)] = 1131,
  [SMALL_STATE(70)] = 1141,
  [SMALL_STATE(71)] = 1151,
  [SMALL_STATE(72)] = 1165,
  [SMALL_STATE(73)] = 1179,
  [SMALL_STATE(74)] = 1193,
  [SMALL_STATE(75)] = 1207,
  [SMALL_STATE(76)] = 1221,
  [SMALL_STATE(77)] = 1231,
  [SMALL_STATE(78)] = 1245,
  [SMALL_STATE(79)] = 1259,
  [SMALL_STATE(80)] = 1273,
  [SMALL_STATE(81)] = 1285,
  [SMALL_STATE(82)] = 1295,
  [SMALL_STATE(83)] = 1309,
  [SMALL_STATE(84)] = 1319,
  [SMALL_STATE(85)] = 1329,
  [SMALL_STATE(86)] = 1338,
  [SMALL_STATE(87)] = 1349,
  [SMALL_STATE(88)] = 1360,
  [SMALL_STATE(89)] = 1371,
  [SMALL_STATE(90)] = 1382,
  [SMALL_STATE(91)] = 1391,
  [SMALL_STATE(92)] = 1402,
  [SMALL_STATE(93)] = 1413,
  [SMALL_STATE(94)] = 1424,
  [SMALL_STATE(95)] = 1435,
  [SMALL_STATE(96)] = 1446,
  [SMALL_STATE(97)] = 1454,
  [SMALL_STATE(98)] = 1462,
  [SMALL_STATE(99)] = 1470,
  [SMALL_STATE(100)] = 1478,
  [SMALL_STATE(101)] = 1486,
  [SMALL_STATE(102)] = 1494,
  [SMALL_STATE(103)] = 1502,
  [SMALL_STATE(104)] = 1510,
  [SMALL_STATE(105)] = 1518,
  [SMALL_STATE(106)] = 1526,
  [SMALL_STATE(107)] = 1534,
  [SMALL_STATE(108)] = 1542,
  [SMALL_STATE(109)] = 1550,
  [SMALL_STATE(110)] = 1558,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__promises, 2),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__promises, 2),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__promises, 1),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__promises, 1),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__promises_repeat1, 2), SHIFT_REPEAT(100),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__promises_repeat1, 2),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__promises_repeat1, 2), SHIFT_REPEAT(16),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__promises_repeat1, 2),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bundle_section, 1),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bundle_section, 1),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value_list, 2),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value_list, 3),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(105),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(110),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_guarded_promises, 1),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_guarded_promises, 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_guarded_body_attributes, 2),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_body_repeat1, 2), SHIFT_REPEAT(100),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_body_repeat1, 2),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_guarded_body_attributes, 1),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__right_value, 1),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, .production_id = 5),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bundle_section, 2),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bundle_section, 2),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_promise, 6, .production_id = 6),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise, 6, .production_id = 6),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bundle_section, 3),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bundle_section, 3),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_promise, 7, .production_id = 6),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise, 7, .production_id = 6),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_promise, 4, .production_id = 6),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise, 4, .production_id = 6),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_half_promise, 4),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_half_promise, 4),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_half_promise, 2),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_half_promise, 2),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_promise, 4, .production_id = 4),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise, 4, .production_id = 4),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_half_promise, 3),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_half_promise, 3),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_promise, 3, .production_id = 4),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise, 3, .production_id = 4),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_promise, 5, .production_id = 4),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise, 5, .production_id = 4),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, .production_id = 5),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_promise, 5, .production_id = 6),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise, 5, .production_id = 6),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bundle_section_repeat1, 2),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_bundle_section_repeat1, 2),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bundle_section_repeat1, 2), SHIFT_REPEAT(14),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_promise, 2, .production_id = 4),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_promise, 2, .production_id = 4),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value_list, 1),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__value_list_repeat1, 2),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__value_list_repeat1, 2), SHIFT_REPEAT(21),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_body_repeat2, 2),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_body_repeat2, 2), SHIFT_REPEAT(20),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_bundle_body_repeat1, 2),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_bundle_body_repeat1, 2), SHIFT_REPEAT(5),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_body, 2),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_guarded_promises, 2),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_class_guarded_promises, 2),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_body, 4),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bundle_body, 3),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_block, 4, .production_id = 1),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bundle_block, 4, .production_id = 2),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_body, 3),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_promise_repeat1, 2),
  [250] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_promise_repeat1, 2), SHIFT_REPEAT(95),
  [253] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__body_attribute, 2),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__body_attribute, 2),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bundle_block, 5, .production_id = 2),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bundle_body, 2),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_block, 5, .production_id = 1),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, .production_id = 3),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [275] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(109),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 5),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [306] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cfengine() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
